version: '3'
services:
  # 開発環境DB
  # db:
  #   image: mysql:5.7
  #   # 日本語化
  #   command:
  #     - mysqld
  #     - --character-set-server=utf8mb4 
  #     - --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - db:/var/lib/mysql
  #   hostname: $MYSQL_HOST
  #   environment:
  #     MYSQL_DATABASE: $MYSQL_DATABASE
  #     MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
  #     MYSQL_USER: $MYSQL_USER

  app:
    build: ./front
    env_file: ./front/.env
    volumes:
      - ./front/build:/app/front/build
      - ./front/public:/app/front/public
      - ./front/src:/app/front/src
      - ./front/package-lock.json:/app/front/package-lock.json
      - ./front/package.json:/app/front/package.json
    ports:
      - '3000:3000'

  server:
    build: ./server
    env_file: ./server/.env
    volumes:
      - ./server/bin:/app/server/bin
      - ./server/routes:/app/server/routes
      - ./server/views:/app/server/views
      - ./server/app.js:/app/server/app.js
      - ./server/package-lock.json:/app/server/package-lock.json
      - ./server/package.json:/app/server/package.json
    ports:
      - '3100:3100'

# volumes:
#   db: